dist: trusty
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull neo4j:3.5.14
  - docker run --name testneo4j -p7474:7474 -p7687:7687 -d -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins --env NEO4J_AUTH=neo4j/scentest neo4j:3.5.14
  - docker ps
