dist: trusty
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull neo4j:latest
  - docker run --name testneo4j -p7474:7474 -p7687:7687 -d --env NEO4J_AUTH=neo4j/scentest neo4j:latest
  - docker ps
