# fly.toml app configuration file generated for scentgraph on 2024-12-25T16:41:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scentgraph'
primary_region = 'arn'

[build]

[env]
  API_URL = "http://localhost:3000"
  PORT = 3004

[http_service]
  internal_port = 3004
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = 'https://scentgraph.fly.dev/api/health'

[deploy]
  strategy = 'canary'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
